# - name: Set new_commit_id
#   ansible.builtin.set_fact:
#     new_commit_id: "git_commit_id: {{ eda_event.payload.commits.0.id }}"
#   when: eda_event is defined

# - name: Set policy description if Git Information is available
#   ansible.builtin.set_fact:
#     desired_policy_body.description: "{{ desired_policy_body.description | regex_replace('git_commit_id\\:\\s([A-Za-z0-9]*)', new_commit_id ) }}"
#   when: eda_event is defined

- name: update policy if bodies dont match
  uri:
    url: https://{{ acs_host }}/v1/policies/{{ policy_body.id }}
    headers:
      Authorization: "Bearer {{ acs_token }}"
    method: PUT
    body: '{{ desired_policy_body  }}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: false
  register: answer
  no_log: false
  changed_when: true
  notify: "Push to git"