- name: Set new_commit_id
  ansible.builtin.set_fact:
    new_commit_id: "git_commit_id: {{ event.commits.0.id }}"
  when: eda_event is defined

- name: Set policy description if Git Information is available
  ansible.builtin.set_fact:
    desired_policy_body.description: "{{ desired_policy_body.description + ' - ' + new_commit_id }}"
  when: eda_event is defined

- name: create new policy
  uri:
    url: https://{{ acs_host }}/v1/policies?enableStrictValidation=true
    headers:
      Authorization: "Bearer {{ acs_token }}"
    method: POST
    body: '{{ policy_body | dict2items | rejectattr("key", "eq", "id") | list | items2dict }}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: false
  register: answer
  no_log: false
  changed_when: true
  notify: "Push to git"
