- name: Echo File Name to be Updated with Git Information
  ansible.builtin.debug:
    msg: "File: {{ policy_file_name }} - was updated via Git"
  when: 
    - ansible_eda.event.payload is defined
    - policy_file_name in eda_event.payload.commits.0.added

- name: Update Policy Information for Files with Git Information Available
  block:
    - name: Check If file was among updated files from Git Event Info
      ansible.builtin.set_fact:
        file_updated: "true"

    - name: Set new_commit_id
      ansible.builtin.set_fact:
        new_commit_id: "git_commit_id: {{ eda_event.payload.commits.0.id }}"

    - name: Set policy description if Git Information is available
      ansible.builtin.set_fact:
        new_description: "{{ desired_policy_body.description | regex_replace('git_commit_id\\:\\s([A-Za-z0-9]*)', new_commit_id ) }}"

    - name: Update policy description if Git Information is available
      ansible.builtin.set_fact:
        new_policy_body: "{{ desired_policy_body | combine(new_item, recursive=true) }}"
      vars:
        new_item: "{ 'description': '{{ new_description }}' }"
      loop: "{{ desired_policy_body | dict2items }}"
      loop_control:
        loop_var: policy_item

    - name: create new policy if Git Information is available
      uri:
        url: https://{{ acs_host }}/v1/policies?enableStrictValidation=true
        headers:
          Authorization: "Bearer {{ acs_token }}"
        method: POST
        body: '{{ new_policy_body | dict2items | rejectattr("key", "eq", "id") | list | items2dict }}'
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: false
      register: answer
      no_log: false
      changed_when: true
      notify: "Push to git"
  when: 
    - ansible_eda.event.payload is defined
    - policy_file_name in eda_event.payload.commits.0.modified

- name: update policy if bodies dont match
  uri:
    url: https://{{ acs_host }}/v1/policies/{{ policy_body.id }}
    headers:
      Authorization: "Bearer {{ acs_token }}"
    method: PUT
    body: '{{ desired_policy_body  }}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: false
  register: answer
  no_log: false
  changed_when: true
  notify: "Push to git"
  when: answer is not defined